
  name: in-orbit-server

  services:
    backend:
      build:
        context: .
        dockerfile: ./Dockerfile
      ports:
        - 3030:3030
      environment:
        DATABASE_URL: postgres://docker:dockerdrizzle@pg/inorbit

    pg:
      image: bitnami/postgresql:13.16.0
      ports:
        - 5432:5432  
      environment: 
        - POSTGRES_USER=docker
        - POSTGRES_PASSWORD=dockerdrizzle 
        - POSTGRES_DB=inorbit

